/**
 * 業種に応じたUI文言（ラベル）の定義マスタ
 * medical: 医療・歯科・クリニック
 * beauty: サロン・エステ・美容
 * general: 一般店舗・サービス業・施設
 */

export const INDUSTRY_LABELS = {
  medical: {
    id: 'medical',
    name: '医療・歯科・クリニック',
    customer: '患者様',
    customerShort: '患者',
    customerCode: '診察券番号 / カルテNo.',
    patientType: '患者種別',
    firstVisit: '初診（新患）',
    firstVisitShort: '初診',
    returningVisit: '再診（通院中）',
    returningVisitShort: '再診',
    service: '診療',
    serviceMenu: '診療メニュー',
    serviceCategory: '診療科目',
    treatment: '治療',
    consultation: '問診・相談',
    visit: '来院・受診',
    visitAction: '受診する',
    visitCount: '受診回数',
    lastVisit: '最終受診',
    schedule: '診療時間・休診日',
    businessOpen: '診療',
    businessClosed: '休診',
    morningSession: '午前診療',
    afternoonSession: '午後診療',
    staff: '医師・衛生士・スタッフ',
    staffRole: '院長・担当医師',
    staffAssignment: '担当医・担当制',
    chart: 'カルテ・患者台帳',
    facilityType: 'クリニック・医院',
    facilityTypeShort: '医院',
    authModalTitle: '患者認証 & カルテ照合',
    returningSubtitle: '前回の受診歴・担当医を引き継いで予約します。',
    newSubtitle: '初めて当院を受診される方のアカウントを作成します。',
    topIntroDefault: '患者様のお悩みやご希望に寄り添い、丁寧な診療を心がけております。WEBより24時間いつでも簡単にご予約いただけます。',
    bookingIntro: '初めてご来院される患者様へ',
  },
  beauty: {
    id: 'beauty',
    name: 'サロン・エステ・美容',
    customer: 'お客様',
    customerShort: 'お客様',
    customerCode: '会員番号 / 顧客No.',
    patientType: '顧客区分',
    firstVisit: '新規（初めて）',
    firstVisitShort: '新規',
    returningVisit: '再来店（リピート）',
    returningVisitShort: '再来店',
    service: '施術・メニュー',
    serviceMenu: '施術メニュー',
    serviceCategory: 'コース・カテゴリ',
    treatment: '施術',
    consultation: 'カウンセリング',
    visit: 'ご来店',
    visitAction: '来店する',
    visitCount: '来店回数',
    lastVisit: '最終来店',
    schedule: '営業時間・定休日',
    businessOpen: '営業',
    businessClosed: '定休',
    morningSession: '午前営業',
    afternoonSession: '午後営業',
    staff: 'スタイリスト・施術者・スタッフ',
    staffRole: '店長・スタイリスト',
    staffAssignment: '指名制・担当スタッフ',
    chart: 'カルテ・顧客台帳',
    facilityType: 'サロン・店舗',
    facilityTypeShort: 'サロン',
    authModalTitle: '会員認証 & 顧客照合',
    returningSubtitle: '前回の施術履歴・担当スタッフを引き継いで予約します。',
    newSubtitle: '初めて当サロンをご利用される方のアカウントを作成します。',
    topIntroDefault: 'お客様のお悩みや理想のスタイルに寄り添い、上質な施術を提供いたします。WEBより24時間いつでも簡単にご予約いただけます。',
    bookingIntro: '初めてご来店されるお客様へ',
  },
  general: {
    id: 'general',
    name: '一般店舗・サービス・施設',
    customer: 'お客様',
    customerShort: 'お客様',
    customerCode: '会員番号 / 顧客ID',
    patientType: '顧客区分',
    firstVisit: '初回ご利用（新規）',
    firstVisitShort: '初回',
    returningVisit: 'リピート（利用歴あり）',
    returningVisitShort: '再利用',
    service: 'サービス・プラン',
    serviceMenu: '予約メニュー',
    serviceCategory: 'サービス種別',
    treatment: 'サービス提供',
    consultation: '事前相談・ヒアリング',
    visit: 'ご来店・ご利用',
    visitAction: '利用する',
    visitCount: '利用回数',
    lastVisit: '最終利用',
    schedule: '営業時間・定休日',
    businessOpen: '営業',
    businessClosed: '定休',
    morningSession: '午前枠',
    afternoonSession: '午後枠',
    staff: '担当者・スタッフ',
    staffRole: '代表・担当者',
    staffAssignment: '担当者指名制',
    chart: '顧客台帳・利用履歴',
    facilityType: '店舗・施設',
    facilityTypeShort: '店舗',
    authModalTitle: 'お客様認証 & 照合',
    returningSubtitle: '前回の利用履歴・担当者を引き継いで予約します。',
    newSubtitle: '初めてご利用される方のアカウントを作成します。',
    topIntroDefault: 'お客様のご要望に合わせ、快適なサービスを提供いたします。WEBより24時間いつでも簡単にご予約いただけます。',
    bookingIntro: '初めてご利用されるお客様へ',
  },
};

/**
 * 指定した業種タイプのラベルセットを取得（フォールバック: medical）
 * @param {string} [industryType='medical']
 * @returns {typeof INDUSTRY_LABELS['medical']}
 */
export function getLabels(industryType = 'medical') {
  return INDUSTRY_LABELS[industryType] || INDUSTRY_LABELS.medical;
}
